namespace Flat_Services_Application.lessor
{
    partial class Requests_Lessor
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Requests_Lessor));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges17 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges18 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel3 = new System.Windows.Forms.Panel();
            this.Services_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.LogOut_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Chat_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Requests_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Pay_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Flat_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Home_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel5 = new System.Windows.Forms.Panel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.panel4 = new System.Windows.Forms.Panel();
            this.Setting_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.label1 = new System.Windows.Forms.Label();
            this.lvRequest = new System.Windows.Forms.ListView();
            this.clmPhone = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.clmName = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.clmRoom = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.btnBrowse = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnNoBrowse = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.panel3.SuspendLayout();
            this.panel5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.panel4.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel3
            // 
            this.panel3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.panel3.Controls.Add(this.Services_btn);
            this.panel3.Controls.Add(this.LogOut_btn);
            this.panel3.Controls.Add(this.Chat_btn);
            this.panel3.Controls.Add(this.Requests_btn);
            this.panel3.Controls.Add(this.Pay_btn);
            this.panel3.Controls.Add(this.Flat_btn);
            this.panel3.Controls.Add(this.Home_btn);
            this.panel3.Controls.Add(this.panel5);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel3.Location = new System.Drawing.Point(0, 0);
            this.panel3.Margin = new System.Windows.Forms.Padding(2);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(240, 659);
            this.panel3.TabIndex = 12;
            // 
            // Services_btn
            // 
            this.Services_btn.AllowAnimations = true;
            this.Services_btn.AllowMouseEffects = true;
            this.Services_btn.AllowToggling = false;
            this.Services_btn.AnimationSpeed = 200;
            this.Services_btn.AutoGenerateColors = false;
            this.Services_btn.AutoRoundBorders = false;
            this.Services_btn.AutoSizeLeftIcon = true;
            this.Services_btn.AutoSizeRightIcon = true;
            this.Services_btn.BackColor = System.Drawing.Color.Transparent;
            this.Services_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Services_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Services_btn.BackgroundImage")));
            this.Services_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Services_btn.ButtonText = "Service";
            this.Services_btn.ButtonTextMarginLeft = 0;
            this.Services_btn.ColorContrastOnClick = 45;
            this.Services_btn.ColorContrastOnHover = 45;
            this.Services_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.Services_btn.CustomizableEdges = borderEdges11;
            this.Services_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Services_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Services_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.Services_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.Services_btn.Dock = System.Windows.Forms.DockStyle.Top;
            this.Services_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Services_btn.Font = new System.Drawing.Font("Century", 22.125F, System.Drawing.FontStyle.Bold);
            this.Services_btn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Services_btn.IconLeft = null;
            this.Services_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Services_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Services_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Services_btn.IconMarginLeft = 11;
            this.Services_btn.IconPadding = 10;
            this.Services_btn.IconRight = null;
            this.Services_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Services_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Services_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Services_btn.IconSize = 25;
            this.Services_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.Services_btn.IdleBorderRadius = 0;
            this.Services_btn.IdleBorderThickness = 0;
            this.Services_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.Services_btn.IdleIconLeftImage = null;
            this.Services_btn.IdleIconRightImage = null;
            this.Services_btn.IndicateFocus = false;
            this.Services_btn.Location = new System.Drawing.Point(0, 487);
            this.Services_btn.Name = "Services_btn";
            this.Services_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Services_btn.OnDisabledState.BorderRadius = 1;
            this.Services_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Services_btn.OnDisabledState.BorderThickness = 1;
            this.Services_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Services_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Services_btn.OnDisabledState.IconLeftImage = null;
            this.Services_btn.OnDisabledState.IconRightImage = null;
            this.Services_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Services_btn.onHoverState.BorderRadius = 1;
            this.Services_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Services_btn.onHoverState.BorderThickness = 1;
            this.Services_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Services_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Services_btn.onHoverState.IconLeftImage = null;
            this.Services_btn.onHoverState.IconRightImage = null;
            this.Services_btn.OnIdleState.BorderColor = System.Drawing.SystemColors.ControlText;
            this.Services_btn.OnIdleState.BorderRadius = 1;
            this.Services_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Services_btn.OnIdleState.BorderThickness = 1;
            this.Services_btn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.Services_btn.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Services_btn.OnIdleState.IconLeftImage = null;
            this.Services_btn.OnIdleState.IconRightImage = null;
            this.Services_btn.OnPressedState.BorderColor = System.Drawing.SystemColors.ControlText;
            this.Services_btn.OnPressedState.BorderRadius = 1;
            this.Services_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Services_btn.OnPressedState.BorderThickness = 1;
            this.Services_btn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.Services_btn.OnPressedState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Services_btn.OnPressedState.IconLeftImage = null;
            this.Services_btn.OnPressedState.IconRightImage = null;
            this.Services_btn.Size = new System.Drawing.Size(240, 77);
            this.Services_btn.TabIndex = 17;
            this.Services_btn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Services_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Services_btn.TextMarginLeft = 0;
            this.Services_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Services_btn.UseDefaultRadiusAndThickness = true;
            this.Services_btn.Click += new System.EventHandler(this.Services_btn_Click);
            // 
            // LogOut_btn
            // 
            this.LogOut_btn.AllowAnimations = true;
            this.LogOut_btn.AllowMouseEffects = true;
            this.LogOut_btn.AllowToggling = false;
            this.LogOut_btn.AnimationSpeed = 200;
            this.LogOut_btn.AutoGenerateColors = false;
            this.LogOut_btn.AutoRoundBorders = false;
            this.LogOut_btn.AutoSizeLeftIcon = true;
            this.LogOut_btn.AutoSizeRightIcon = true;
            this.LogOut_btn.BackColor = System.Drawing.Color.Transparent;
            this.LogOut_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.LogOut_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("LogOut_btn.BackgroundImage")));
            this.LogOut_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LogOut_btn.ButtonText = "Log Out";
            this.LogOut_btn.ButtonTextMarginLeft = 0;
            this.LogOut_btn.ColorContrastOnClick = 45;
            this.LogOut_btn.ColorContrastOnHover = 45;
            this.LogOut_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.LogOut_btn.CustomizableEdges = borderEdges12;
            this.LogOut_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.LogOut_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LogOut_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.LogOut_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.LogOut_btn.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.LogOut_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.LogOut_btn.Font = new System.Drawing.Font("Century", 22.125F, System.Drawing.FontStyle.Bold);
            this.LogOut_btn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.LogOut_btn.IconLeft = null;
            this.LogOut_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.LogOut_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.LogOut_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.LogOut_btn.IconMarginLeft = 11;
            this.LogOut_btn.IconPadding = 10;
            this.LogOut_btn.IconRight = null;
            this.LogOut_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.LogOut_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.LogOut_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.LogOut_btn.IconSize = 25;
            this.LogOut_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.LogOut_btn.IdleBorderRadius = 0;
            this.LogOut_btn.IdleBorderThickness = 0;
            this.LogOut_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.LogOut_btn.IdleIconLeftImage = null;
            this.LogOut_btn.IdleIconRightImage = null;
            this.LogOut_btn.IndicateFocus = false;
            this.LogOut_btn.Location = new System.Drawing.Point(0, 564);
            this.LogOut_btn.Name = "LogOut_btn";
            this.LogOut_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LogOut_btn.OnDisabledState.BorderRadius = 1;
            this.LogOut_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LogOut_btn.OnDisabledState.BorderThickness = 1;
            this.LogOut_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LogOut_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LogOut_btn.OnDisabledState.IconLeftImage = null;
            this.LogOut_btn.OnDisabledState.IconRightImage = null;
            this.LogOut_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.LogOut_btn.onHoverState.BorderRadius = 1;
            this.LogOut_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LogOut_btn.onHoverState.BorderThickness = 1;
            this.LogOut_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.LogOut_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.LogOut_btn.onHoverState.IconLeftImage = null;
            this.LogOut_btn.onHoverState.IconRightImage = null;
            this.LogOut_btn.OnIdleState.BorderColor = System.Drawing.SystemColors.ControlText;
            this.LogOut_btn.OnIdleState.BorderRadius = 1;
            this.LogOut_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LogOut_btn.OnIdleState.BorderThickness = 1;
            this.LogOut_btn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.LogOut_btn.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.LogOut_btn.OnIdleState.IconLeftImage = null;
            this.LogOut_btn.OnIdleState.IconRightImage = null;
            this.LogOut_btn.OnPressedState.BorderColor = System.Drawing.SystemColors.ControlText;
            this.LogOut_btn.OnPressedState.BorderRadius = 1;
            this.LogOut_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LogOut_btn.OnPressedState.BorderThickness = 1;
            this.LogOut_btn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.LogOut_btn.OnPressedState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.LogOut_btn.OnPressedState.IconLeftImage = null;
            this.LogOut_btn.OnPressedState.IconRightImage = null;
            this.LogOut_btn.Size = new System.Drawing.Size(240, 95);
            this.LogOut_btn.TabIndex = 15;
            this.LogOut_btn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.LogOut_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.LogOut_btn.TextMarginLeft = 0;
            this.LogOut_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.LogOut_btn.UseDefaultRadiusAndThickness = true;
            this.LogOut_btn.Click += new System.EventHandler(this.LogOut_btn_Click);
            // 
            // Chat_btn
            // 
            this.Chat_btn.AllowAnimations = true;
            this.Chat_btn.AllowMouseEffects = true;
            this.Chat_btn.AllowToggling = false;
            this.Chat_btn.AnimationSpeed = 200;
            this.Chat_btn.AutoGenerateColors = false;
            this.Chat_btn.AutoRoundBorders = false;
            this.Chat_btn.AutoSizeLeftIcon = true;
            this.Chat_btn.AutoSizeRightIcon = true;
            this.Chat_btn.BackColor = System.Drawing.Color.Transparent;
            this.Chat_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Chat_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Chat_btn.BackgroundImage")));
            this.Chat_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Chat_btn.ButtonText = "Chat";
            this.Chat_btn.ButtonTextMarginLeft = 0;
            this.Chat_btn.ColorContrastOnClick = 45;
            this.Chat_btn.ColorContrastOnHover = 45;
            this.Chat_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.Chat_btn.CustomizableEdges = borderEdges13;
            this.Chat_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Chat_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Chat_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.Chat_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.Chat_btn.Dock = System.Windows.Forms.DockStyle.Top;
            this.Chat_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Chat_btn.Font = new System.Drawing.Font("Century", 22.125F, System.Drawing.FontStyle.Bold);
            this.Chat_btn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Chat_btn.IconLeft = null;
            this.Chat_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Chat_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Chat_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Chat_btn.IconMarginLeft = 11;
            this.Chat_btn.IconPadding = 10;
            this.Chat_btn.IconRight = null;
            this.Chat_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Chat_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Chat_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Chat_btn.IconSize = 25;
            this.Chat_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.Chat_btn.IdleBorderRadius = 0;
            this.Chat_btn.IdleBorderThickness = 0;
            this.Chat_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.Chat_btn.IdleIconLeftImage = null;
            this.Chat_btn.IdleIconRightImage = null;
            this.Chat_btn.IndicateFocus = false;
            this.Chat_btn.Location = new System.Drawing.Point(0, 410);
            this.Chat_btn.Name = "Chat_btn";
            this.Chat_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Chat_btn.OnDisabledState.BorderRadius = 1;
            this.Chat_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Chat_btn.OnDisabledState.BorderThickness = 1;
            this.Chat_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Chat_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Chat_btn.OnDisabledState.IconLeftImage = null;
            this.Chat_btn.OnDisabledState.IconRightImage = null;
            this.Chat_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Chat_btn.onHoverState.BorderRadius = 1;
            this.Chat_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Chat_btn.onHoverState.BorderThickness = 1;
            this.Chat_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Chat_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Chat_btn.onHoverState.IconLeftImage = null;
            this.Chat_btn.onHoverState.IconRightImage = null;
            this.Chat_btn.OnIdleState.BorderColor = System.Drawing.SystemColors.ControlText;
            this.Chat_btn.OnIdleState.BorderRadius = 1;
            this.Chat_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Chat_btn.OnIdleState.BorderThickness = 1;
            this.Chat_btn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.Chat_btn.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Chat_btn.OnIdleState.IconLeftImage = null;
            this.Chat_btn.OnIdleState.IconRightImage = null;
            this.Chat_btn.OnPressedState.BorderColor = System.Drawing.SystemColors.ControlText;
            this.Chat_btn.OnPressedState.BorderRadius = 1;
            this.Chat_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Chat_btn.OnPressedState.BorderThickness = 1;
            this.Chat_btn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.Chat_btn.OnPressedState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Chat_btn.OnPressedState.IconLeftImage = null;
            this.Chat_btn.OnPressedState.IconRightImage = null;
            this.Chat_btn.Size = new System.Drawing.Size(240, 77);
            this.Chat_btn.TabIndex = 13;
            this.Chat_btn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Chat_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Chat_btn.TextMarginLeft = 0;
            this.Chat_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Chat_btn.UseDefaultRadiusAndThickness = true;
            this.Chat_btn.Click += new System.EventHandler(this.Chat_btn_Click);
            // 
            // Requests_btn
            // 
            this.Requests_btn.AllowAnimations = true;
            this.Requests_btn.AllowMouseEffects = true;
            this.Requests_btn.AllowToggling = false;
            this.Requests_btn.AnimationSpeed = 200;
            this.Requests_btn.AutoGenerateColors = false;
            this.Requests_btn.AutoRoundBorders = false;
            this.Requests_btn.AutoSizeLeftIcon = true;
            this.Requests_btn.AutoSizeRightIcon = true;
            this.Requests_btn.BackColor = System.Drawing.Color.Transparent;
            this.Requests_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Requests_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Requests_btn.BackgroundImage")));
            this.Requests_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Requests_btn.ButtonText = "Request";
            this.Requests_btn.ButtonTextMarginLeft = 0;
            this.Requests_btn.ColorContrastOnClick = 45;
            this.Requests_btn.ColorContrastOnHover = 45;
            this.Requests_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.Requests_btn.CustomizableEdges = borderEdges14;
            this.Requests_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Requests_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Requests_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.Requests_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.Requests_btn.Dock = System.Windows.Forms.DockStyle.Top;
            this.Requests_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Requests_btn.Font = new System.Drawing.Font("Century", 22.125F, System.Drawing.FontStyle.Bold);
            this.Requests_btn.ForeColor = System.Drawing.Color.White;
            this.Requests_btn.IconLeft = null;
            this.Requests_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Requests_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Requests_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Requests_btn.IconMarginLeft = 11;
            this.Requests_btn.IconPadding = 10;
            this.Requests_btn.IconRight = null;
            this.Requests_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Requests_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Requests_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Requests_btn.IconSize = 25;
            this.Requests_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.Requests_btn.IdleBorderRadius = 0;
            this.Requests_btn.IdleBorderThickness = 0;
            this.Requests_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.Requests_btn.IdleIconLeftImage = null;
            this.Requests_btn.IdleIconRightImage = null;
            this.Requests_btn.IndicateFocus = false;
            this.Requests_btn.Location = new System.Drawing.Point(0, 333);
            this.Requests_btn.Name = "Requests_btn";
            this.Requests_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Requests_btn.OnDisabledState.BorderRadius = 1;
            this.Requests_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Requests_btn.OnDisabledState.BorderThickness = 1;
            this.Requests_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Requests_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Requests_btn.OnDisabledState.IconLeftImage = null;
            this.Requests_btn.OnDisabledState.IconRightImage = null;
            this.Requests_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Requests_btn.onHoverState.BorderRadius = 1;
            this.Requests_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Requests_btn.onHoverState.BorderThickness = 1;
            this.Requests_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Requests_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Requests_btn.onHoverState.IconLeftImage = null;
            this.Requests_btn.onHoverState.IconRightImage = null;
            this.Requests_btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Requests_btn.OnIdleState.BorderRadius = 1;
            this.Requests_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Requests_btn.OnIdleState.BorderThickness = 1;
            this.Requests_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Requests_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Requests_btn.OnIdleState.IconLeftImage = null;
            this.Requests_btn.OnIdleState.IconRightImage = null;
            this.Requests_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Requests_btn.OnPressedState.BorderRadius = 1;
            this.Requests_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Requests_btn.OnPressedState.BorderThickness = 1;
            this.Requests_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Requests_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Requests_btn.OnPressedState.IconLeftImage = null;
            this.Requests_btn.OnPressedState.IconRightImage = null;
            this.Requests_btn.Size = new System.Drawing.Size(240, 77);
            this.Requests_btn.TabIndex = 10;
            this.Requests_btn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Requests_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Requests_btn.TextMarginLeft = 0;
            this.Requests_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Requests_btn.UseDefaultRadiusAndThickness = true;
            this.Requests_btn.Click += new System.EventHandler(this.Requests_btn_Click);
            // 
            // Pay_btn
            // 
            this.Pay_btn.AllowAnimations = true;
            this.Pay_btn.AllowMouseEffects = true;
            this.Pay_btn.AllowToggling = false;
            this.Pay_btn.AnimationSpeed = 200;
            this.Pay_btn.AutoGenerateColors = false;
            this.Pay_btn.AutoRoundBorders = false;
            this.Pay_btn.AutoSizeLeftIcon = true;
            this.Pay_btn.AutoSizeRightIcon = true;
            this.Pay_btn.BackColor = System.Drawing.Color.Transparent;
            this.Pay_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Pay_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Pay_btn.BackgroundImage")));
            this.Pay_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Pay_btn.ButtonText = "Payment";
            this.Pay_btn.ButtonTextMarginLeft = 0;
            this.Pay_btn.ColorContrastOnClick = 45;
            this.Pay_btn.ColorContrastOnHover = 45;
            this.Pay_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges15.BottomLeft = true;
            borderEdges15.BottomRight = true;
            borderEdges15.TopLeft = true;
            borderEdges15.TopRight = true;
            this.Pay_btn.CustomizableEdges = borderEdges15;
            this.Pay_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Pay_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Pay_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.Pay_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.Pay_btn.Dock = System.Windows.Forms.DockStyle.Top;
            this.Pay_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Pay_btn.Font = new System.Drawing.Font("Century", 22.125F, System.Drawing.FontStyle.Bold);
            this.Pay_btn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Pay_btn.IconLeft = null;
            this.Pay_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Pay_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Pay_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Pay_btn.IconMarginLeft = 11;
            this.Pay_btn.IconPadding = 10;
            this.Pay_btn.IconRight = null;
            this.Pay_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Pay_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Pay_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Pay_btn.IconSize = 25;
            this.Pay_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.Pay_btn.IdleBorderRadius = 0;
            this.Pay_btn.IdleBorderThickness = 0;
            this.Pay_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.Pay_btn.IdleIconLeftImage = null;
            this.Pay_btn.IdleIconRightImage = null;
            this.Pay_btn.IndicateFocus = false;
            this.Pay_btn.Location = new System.Drawing.Point(0, 256);
            this.Pay_btn.Name = "Pay_btn";
            this.Pay_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Pay_btn.OnDisabledState.BorderRadius = 1;
            this.Pay_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Pay_btn.OnDisabledState.BorderThickness = 1;
            this.Pay_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Pay_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Pay_btn.OnDisabledState.IconLeftImage = null;
            this.Pay_btn.OnDisabledState.IconRightImage = null;
            this.Pay_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Pay_btn.onHoverState.BorderRadius = 1;
            this.Pay_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Pay_btn.onHoverState.BorderThickness = 1;
            this.Pay_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Pay_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Pay_btn.onHoverState.IconLeftImage = null;
            this.Pay_btn.onHoverState.IconRightImage = null;
            this.Pay_btn.OnIdleState.BorderColor = System.Drawing.SystemColors.ControlText;
            this.Pay_btn.OnIdleState.BorderRadius = 1;
            this.Pay_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Pay_btn.OnIdleState.BorderThickness = 1;
            this.Pay_btn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.Pay_btn.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Pay_btn.OnIdleState.IconLeftImage = null;
            this.Pay_btn.OnIdleState.IconRightImage = null;
            this.Pay_btn.OnPressedState.BorderColor = System.Drawing.SystemColors.ControlText;
            this.Pay_btn.OnPressedState.BorderRadius = 1;
            this.Pay_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Pay_btn.OnPressedState.BorderThickness = 1;
            this.Pay_btn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.Pay_btn.OnPressedState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Pay_btn.OnPressedState.IconLeftImage = null;
            this.Pay_btn.OnPressedState.IconRightImage = null;
            this.Pay_btn.Size = new System.Drawing.Size(240, 77);
            this.Pay_btn.TabIndex = 11;
            this.Pay_btn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Pay_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Pay_btn.TextMarginLeft = 0;
            this.Pay_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Pay_btn.UseDefaultRadiusAndThickness = true;
            this.Pay_btn.Click += new System.EventHandler(this.Pay_btn_Click);
            // 
            // Flat_btn
            // 
            this.Flat_btn.AllowAnimations = true;
            this.Flat_btn.AllowMouseEffects = true;
            this.Flat_btn.AllowToggling = false;
            this.Flat_btn.AnimationSpeed = 200;
            this.Flat_btn.AutoGenerateColors = false;
            this.Flat_btn.AutoRoundBorders = false;
            this.Flat_btn.AutoSizeLeftIcon = true;
            this.Flat_btn.AutoSizeRightIcon = true;
            this.Flat_btn.BackColor = System.Drawing.Color.Transparent;
            this.Flat_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Flat_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Flat_btn.BackgroundImage")));
            this.Flat_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Flat_btn.ButtonText = "Flat Guide";
            this.Flat_btn.ButtonTextMarginLeft = 0;
            this.Flat_btn.ColorContrastOnClick = 45;
            this.Flat_btn.ColorContrastOnHover = 45;
            this.Flat_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges16.BottomLeft = true;
            borderEdges16.BottomRight = true;
            borderEdges16.TopLeft = true;
            borderEdges16.TopRight = true;
            this.Flat_btn.CustomizableEdges = borderEdges16;
            this.Flat_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Flat_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Flat_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.Flat_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.Flat_btn.Dock = System.Windows.Forms.DockStyle.Top;
            this.Flat_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Flat_btn.Font = new System.Drawing.Font("Century", 22.125F, System.Drawing.FontStyle.Bold);
            this.Flat_btn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Flat_btn.IconLeft = null;
            this.Flat_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Flat_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Flat_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Flat_btn.IconMarginLeft = 11;
            this.Flat_btn.IconPadding = 10;
            this.Flat_btn.IconRight = null;
            this.Flat_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Flat_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Flat_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Flat_btn.IconSize = 25;
            this.Flat_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.Flat_btn.IdleBorderRadius = 0;
            this.Flat_btn.IdleBorderThickness = 0;
            this.Flat_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.Flat_btn.IdleIconLeftImage = null;
            this.Flat_btn.IdleIconRightImage = null;
            this.Flat_btn.IndicateFocus = false;
            this.Flat_btn.Location = new System.Drawing.Point(0, 179);
            this.Flat_btn.Name = "Flat_btn";
            this.Flat_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Flat_btn.OnDisabledState.BorderRadius = 1;
            this.Flat_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Flat_btn.OnDisabledState.BorderThickness = 1;
            this.Flat_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Flat_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Flat_btn.OnDisabledState.IconLeftImage = null;
            this.Flat_btn.OnDisabledState.IconRightImage = null;
            this.Flat_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Flat_btn.onHoverState.BorderRadius = 1;
            this.Flat_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Flat_btn.onHoverState.BorderThickness = 1;
            this.Flat_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Flat_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Flat_btn.onHoverState.IconLeftImage = null;
            this.Flat_btn.onHoverState.IconRightImage = null;
            this.Flat_btn.OnIdleState.BorderColor = System.Drawing.SystemColors.ControlText;
            this.Flat_btn.OnIdleState.BorderRadius = 1;
            this.Flat_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Flat_btn.OnIdleState.BorderThickness = 1;
            this.Flat_btn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.Flat_btn.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Flat_btn.OnIdleState.IconLeftImage = null;
            this.Flat_btn.OnIdleState.IconRightImage = null;
            this.Flat_btn.OnPressedState.BorderColor = System.Drawing.SystemColors.ControlText;
            this.Flat_btn.OnPressedState.BorderRadius = 1;
            this.Flat_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Flat_btn.OnPressedState.BorderThickness = 1;
            this.Flat_btn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.Flat_btn.OnPressedState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Flat_btn.OnPressedState.IconLeftImage = null;
            this.Flat_btn.OnPressedState.IconRightImage = null;
            this.Flat_btn.Size = new System.Drawing.Size(240, 77);
            this.Flat_btn.TabIndex = 12;
            this.Flat_btn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Flat_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Flat_btn.TextMarginLeft = 0;
            this.Flat_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Flat_btn.UseDefaultRadiusAndThickness = true;
            this.Flat_btn.Click += new System.EventHandler(this.Flat_btn_Click);
            // 
            // Home_btn
            // 
            this.Home_btn.AllowAnimations = true;
            this.Home_btn.AllowMouseEffects = true;
            this.Home_btn.AllowToggling = false;
            this.Home_btn.AnimationSpeed = 200;
            this.Home_btn.AutoGenerateColors = false;
            this.Home_btn.AutoRoundBorders = false;
            this.Home_btn.AutoSizeLeftIcon = true;
            this.Home_btn.AutoSizeRightIcon = true;
            this.Home_btn.BackColor = System.Drawing.Color.Transparent;
            this.Home_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Home_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Home_btn.BackgroundImage")));
            this.Home_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Home_btn.ButtonText = "Home";
            this.Home_btn.ButtonTextMarginLeft = 0;
            this.Home_btn.ColorContrastOnClick = 45;
            this.Home_btn.ColorContrastOnHover = 45;
            this.Home_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges17.BottomLeft = true;
            borderEdges17.BottomRight = true;
            borderEdges17.TopLeft = true;
            borderEdges17.TopRight = true;
            this.Home_btn.CustomizableEdges = borderEdges17;
            this.Home_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Home_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Home_btn.DisabledFillColor = System.Drawing.Color.Empty;
            this.Home_btn.DisabledForecolor = System.Drawing.Color.Empty;
            this.Home_btn.Dock = System.Windows.Forms.DockStyle.Top;
            this.Home_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Home_btn.Font = new System.Drawing.Font("Century", 22.125F, System.Drawing.FontStyle.Bold);
            this.Home_btn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Home_btn.IconLeft = null;
            this.Home_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Home_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Home_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Home_btn.IconMarginLeft = 11;
            this.Home_btn.IconPadding = 10;
            this.Home_btn.IconRight = null;
            this.Home_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Home_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Home_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Home_btn.IconSize = 25;
            this.Home_btn.IdleBorderColor = System.Drawing.Color.Empty;
            this.Home_btn.IdleBorderRadius = 0;
            this.Home_btn.IdleBorderThickness = 0;
            this.Home_btn.IdleFillColor = System.Drawing.Color.Empty;
            this.Home_btn.IdleIconLeftImage = null;
            this.Home_btn.IdleIconRightImage = null;
            this.Home_btn.IndicateFocus = false;
            this.Home_btn.Location = new System.Drawing.Point(0, 102);
            this.Home_btn.Name = "Home_btn";
            this.Home_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Home_btn.OnDisabledState.BorderRadius = 1;
            this.Home_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Home_btn.OnDisabledState.BorderThickness = 1;
            this.Home_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Home_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Home_btn.OnDisabledState.IconLeftImage = null;
            this.Home_btn.OnDisabledState.IconRightImage = null;
            this.Home_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Home_btn.onHoverState.BorderRadius = 1;
            this.Home_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Home_btn.onHoverState.BorderThickness = 1;
            this.Home_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.Home_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Home_btn.onHoverState.IconLeftImage = null;
            this.Home_btn.onHoverState.IconRightImage = null;
            this.Home_btn.OnIdleState.BorderColor = System.Drawing.SystemColors.ControlText;
            this.Home_btn.OnIdleState.BorderRadius = 1;
            this.Home_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Home_btn.OnIdleState.BorderThickness = 1;
            this.Home_btn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.Home_btn.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Home_btn.OnIdleState.IconLeftImage = null;
            this.Home_btn.OnIdleState.IconRightImage = null;
            this.Home_btn.OnPressedState.BorderColor = System.Drawing.SystemColors.ControlText;
            this.Home_btn.OnPressedState.BorderRadius = 1;
            this.Home_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Home_btn.OnPressedState.BorderThickness = 1;
            this.Home_btn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.Home_btn.OnPressedState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Home_btn.OnPressedState.IconLeftImage = null;
            this.Home_btn.OnPressedState.IconRightImage = null;
            this.Home_btn.Size = new System.Drawing.Size(240, 77);
            this.Home_btn.TabIndex = 1;
            this.Home_btn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Home_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Home_btn.TextMarginLeft = 0;
            this.Home_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Home_btn.UseDefaultRadiusAndThickness = true;
            this.Home_btn.Click += new System.EventHandler(this.Home_btn_Click);
            // 
            // panel5
            // 
            this.panel5.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panel5.Controls.Add(this.pictureBox1);
            this.panel5.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel5.Location = new System.Drawing.Point(0, 0);
            this.panel5.Margin = new System.Windows.Forms.Padding(2);
            this.panel5.Name = "panel5";
            this.panel5.Size = new System.Drawing.Size(240, 102);
            this.panel5.TabIndex = 0;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pictureBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(0, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(240, 102);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 10;
            this.pictureBox1.TabStop = false;
            // 
            // panel4
            // 
            this.panel4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.panel4.Controls.Add(this.Setting_btn);
            this.panel4.Controls.Add(this.bunifuLabel1);
            this.panel4.Controls.Add(this.label1);
            this.panel4.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel4.Location = new System.Drawing.Point(240, 0);
            this.panel4.Margin = new System.Windows.Forms.Padding(2);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(943, 102);
            this.panel4.TabIndex = 13;
            // 
            // Setting_btn
            // 
            this.Setting_btn.AllowAnimations = true;
            this.Setting_btn.AllowBorderColorChanges = true;
            this.Setting_btn.AllowMouseEffects = true;
            this.Setting_btn.AnimationSpeed = 200;
            this.Setting_btn.BackColor = System.Drawing.Color.Transparent;
            this.Setting_btn.BackgroundColor = System.Drawing.Color.FloralWhite;
            this.Setting_btn.BorderColor = System.Drawing.Color.FloralWhite;
            this.Setting_btn.BorderRadius = 1;
            this.Setting_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.Setting_btn.BorderThickness = 1;
            this.Setting_btn.ColorContrastOnClick = 30;
            this.Setting_btn.ColorContrastOnHover = 30;
            this.Setting_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges18.BottomLeft = true;
            borderEdges18.BottomRight = true;
            borderEdges18.TopLeft = true;
            borderEdges18.TopRight = true;
            this.Setting_btn.CustomizableEdges = borderEdges18;
            this.Setting_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Setting_btn.Image = ((System.Drawing.Image)(resources.GetObject("Setting_btn.Image")));
            this.Setting_btn.ImageMargin = new System.Windows.Forms.Padding(0);
            this.Setting_btn.Location = new System.Drawing.Point(876, 16);
            this.Setting_btn.Name = "Setting_btn";
            this.Setting_btn.RoundBorders = true;
            this.Setting_btn.ShowBorders = true;
            this.Setting_btn.Size = new System.Drawing.Size(55, 55);
            this.Setting_btn.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            this.Setting_btn.TabIndex = 10;
            this.Setting_btn.Click += new System.EventHandler(this.Setting_btn_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century", 22.125F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(9, 27);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(219, 44);
            this.bunifuLabel1.TabIndex = 10;
            this.bunifuLabel1.Text = "REQUESTS";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Century", 22.125F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(4, 27);
            this.label1.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(0, 44);
            this.label1.TabIndex = 0;
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // lvRequest
            // 
            this.lvRequest.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.clmPhone,
            this.clmName,
            this.clmRoom});
            this.lvRequest.FullRowSelect = true;
            this.lvRequest.GridLines = true;
            this.lvRequest.HideSelection = false;
            this.lvRequest.Location = new System.Drawing.Point(252, 227);
            this.lvRequest.Name = "lvRequest";
            this.lvRequest.Size = new System.Drawing.Size(917, 420);
            this.lvRequest.TabIndex = 14;
            this.lvRequest.UseCompatibleStateImageBehavior = false;
            this.lvRequest.View = System.Windows.Forms.View.Details;
            this.lvRequest.SelectedIndexChanged += new System.EventHandler(this.lvRequest_SelectedIndexChanged);
            // 
            // clmPhone
            // 
            this.clmPhone.Text = "Account Phone Number";
            this.clmPhone.Width = 247;
            // 
            // clmName
            // 
            this.clmName.Text = "Name";
            this.clmName.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.clmName.Width = 291;
            // 
            // clmRoom
            // 
            this.clmRoom.Text = "Room";
            this.clmRoom.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.clmRoom.Width = 147;
            // 
            // btnBrowse
            // 
            this.btnBrowse.AllowAnimations = true;
            this.btnBrowse.AllowMouseEffects = true;
            this.btnBrowse.AllowToggling = false;
            this.btnBrowse.AnimationSpeed = 200;
            this.btnBrowse.AutoGenerateColors = false;
            this.btnBrowse.AutoRoundBorders = false;
            this.btnBrowse.AutoSizeLeftIcon = true;
            this.btnBrowse.AutoSizeRightIcon = true;
            this.btnBrowse.BackColor = System.Drawing.Color.Transparent;
            this.btnBrowse.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnBrowse.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBrowse.BackgroundImage")));
            this.btnBrowse.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBrowse.ButtonText = "Browse";
            this.btnBrowse.ButtonTextMarginLeft = 0;
            this.btnBrowse.ColorContrastOnClick = 45;
            this.btnBrowse.ColorContrastOnHover = 45;
            this.btnBrowse.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges19.BottomLeft = true;
            borderEdges19.BottomRight = true;
            borderEdges19.TopLeft = true;
            borderEdges19.TopRight = true;
            this.btnBrowse.CustomizableEdges = borderEdges19;
            this.btnBrowse.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBrowse.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBrowse.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnBrowse.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnBrowse.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBrowse.Font = new System.Drawing.Font("Century", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBrowse.ForeColor = System.Drawing.Color.White;
            this.btnBrowse.IconLeft = null;
            this.btnBrowse.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBrowse.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBrowse.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBrowse.IconMarginLeft = 11;
            this.btnBrowse.IconPadding = 10;
            this.btnBrowse.IconRight = null;
            this.btnBrowse.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBrowse.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBrowse.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBrowse.IconSize = 25;
            this.btnBrowse.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnBrowse.IdleBorderRadius = 0;
            this.btnBrowse.IdleBorderThickness = 0;
            this.btnBrowse.IdleFillColor = System.Drawing.Color.Empty;
            this.btnBrowse.IdleIconLeftImage = null;
            this.btnBrowse.IdleIconRightImage = null;
            this.btnBrowse.IndicateFocus = false;
            this.btnBrowse.Location = new System.Drawing.Point(1065, 125);
            this.btnBrowse.Name = "btnBrowse";
            this.btnBrowse.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBrowse.OnDisabledState.BorderRadius = 1;
            this.btnBrowse.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBrowse.OnDisabledState.BorderThickness = 1;
            this.btnBrowse.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBrowse.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBrowse.OnDisabledState.IconLeftImage = null;
            this.btnBrowse.OnDisabledState.IconRightImage = null;
            this.btnBrowse.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.btnBrowse.onHoverState.BorderRadius = 1;
            this.btnBrowse.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBrowse.onHoverState.BorderThickness = 1;
            this.btnBrowse.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.btnBrowse.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBrowse.onHoverState.IconLeftImage = null;
            this.btnBrowse.onHoverState.IconRightImage = null;
            this.btnBrowse.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.btnBrowse.OnIdleState.BorderRadius = 1;
            this.btnBrowse.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBrowse.OnIdleState.BorderThickness = 1;
            this.btnBrowse.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.btnBrowse.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBrowse.OnIdleState.IconLeftImage = null;
            this.btnBrowse.OnIdleState.IconRightImage = null;
            this.btnBrowse.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.btnBrowse.OnPressedState.BorderRadius = 1;
            this.btnBrowse.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBrowse.OnPressedState.BorderThickness = 1;
            this.btnBrowse.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.btnBrowse.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBrowse.OnPressedState.IconLeftImage = null;
            this.btnBrowse.OnPressedState.IconRightImage = null;
            this.btnBrowse.Size = new System.Drawing.Size(106, 37);
            this.btnBrowse.TabIndex = 15;
            this.btnBrowse.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBrowse.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBrowse.TextMarginLeft = 0;
            this.btnBrowse.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBrowse.UseDefaultRadiusAndThickness = true;
            this.btnBrowse.Click += new System.EventHandler(this.btnBrowse_Click);
            // 
            // btnNoBrowse
            // 
            this.btnNoBrowse.AllowAnimations = true;
            this.btnNoBrowse.AllowMouseEffects = true;
            this.btnNoBrowse.AllowToggling = false;
            this.btnNoBrowse.AnimationSpeed = 200;
            this.btnNoBrowse.AutoGenerateColors = false;
            this.btnNoBrowse.AutoRoundBorders = false;
            this.btnNoBrowse.AutoSizeLeftIcon = true;
            this.btnNoBrowse.AutoSizeRightIcon = true;
            this.btnNoBrowse.BackColor = System.Drawing.Color.Transparent;
            this.btnNoBrowse.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnNoBrowse.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNoBrowse.BackgroundImage")));
            this.btnNoBrowse.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNoBrowse.ButtonText = "Delete";
            this.btnNoBrowse.ButtonTextMarginLeft = 0;
            this.btnNoBrowse.ColorContrastOnClick = 45;
            this.btnNoBrowse.ColorContrastOnHover = 45;
            this.btnNoBrowse.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges20.BottomLeft = true;
            borderEdges20.BottomRight = true;
            borderEdges20.TopLeft = true;
            borderEdges20.TopRight = true;
            this.btnNoBrowse.CustomizableEdges = borderEdges20;
            this.btnNoBrowse.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNoBrowse.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNoBrowse.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnNoBrowse.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnNoBrowse.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnNoBrowse.Font = new System.Drawing.Font("Century", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnNoBrowse.ForeColor = System.Drawing.Color.White;
            this.btnNoBrowse.IconLeft = null;
            this.btnNoBrowse.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNoBrowse.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnNoBrowse.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnNoBrowse.IconMarginLeft = 11;
            this.btnNoBrowse.IconPadding = 10;
            this.btnNoBrowse.IconRight = null;
            this.btnNoBrowse.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnNoBrowse.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnNoBrowse.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnNoBrowse.IconSize = 25;
            this.btnNoBrowse.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnNoBrowse.IdleBorderRadius = 0;
            this.btnNoBrowse.IdleBorderThickness = 0;
            this.btnNoBrowse.IdleFillColor = System.Drawing.Color.Empty;
            this.btnNoBrowse.IdleIconLeftImage = null;
            this.btnNoBrowse.IdleIconRightImage = null;
            this.btnNoBrowse.IndicateFocus = false;
            this.btnNoBrowse.Location = new System.Drawing.Point(1065, 179);
            this.btnNoBrowse.Name = "btnNoBrowse";
            this.btnNoBrowse.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNoBrowse.OnDisabledState.BorderRadius = 1;
            this.btnNoBrowse.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNoBrowse.OnDisabledState.BorderThickness = 1;
            this.btnNoBrowse.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNoBrowse.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNoBrowse.OnDisabledState.IconLeftImage = null;
            this.btnNoBrowse.OnDisabledState.IconRightImage = null;
            this.btnNoBrowse.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.btnNoBrowse.onHoverState.BorderRadius = 1;
            this.btnNoBrowse.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNoBrowse.onHoverState.BorderThickness = 1;
            this.btnNoBrowse.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.btnNoBrowse.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnNoBrowse.onHoverState.IconLeftImage = null;
            this.btnNoBrowse.onHoverState.IconRightImage = null;
            this.btnNoBrowse.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.btnNoBrowse.OnIdleState.BorderRadius = 1;
            this.btnNoBrowse.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNoBrowse.OnIdleState.BorderThickness = 1;
            this.btnNoBrowse.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.btnNoBrowse.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnNoBrowse.OnIdleState.IconLeftImage = null;
            this.btnNoBrowse.OnIdleState.IconRightImage = null;
            this.btnNoBrowse.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.btnNoBrowse.OnPressedState.BorderRadius = 1;
            this.btnNoBrowse.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNoBrowse.OnPressedState.BorderThickness = 1;
            this.btnNoBrowse.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(53)))), ((int)(((byte)(65)))));
            this.btnNoBrowse.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnNoBrowse.OnPressedState.IconLeftImage = null;
            this.btnNoBrowse.OnPressedState.IconRightImage = null;
            this.btnNoBrowse.Size = new System.Drawing.Size(106, 37);
            this.btnNoBrowse.TabIndex = 16;
            this.btnNoBrowse.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNoBrowse.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnNoBrowse.TextMarginLeft = 0;
            this.btnNoBrowse.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnNoBrowse.UseDefaultRadiusAndThickness = true;
            this.btnNoBrowse.Click += new System.EventHandler(this.btnNoBrowse_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Century", 22F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(252, 118);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(292, 44);
            this.bunifuLabel2.TabIndex = 17;
            this.bunifuLabel2.Text = "List of Requests";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Requests_Lessor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1183, 659);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.btnNoBrowse);
            this.Controls.Add(this.btnBrowse);
            this.Controls.Add(this.lvRequest);
            this.Controls.Add(this.panel4);
            this.Controls.Add(this.panel3);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.Name = "Requests_Lessor";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Flat Service";
            this.Load += new System.EventHandler(this.Requests_Lessor_Load);
            this.panel3.ResumeLayout(false);
            this.panel5.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.panel4.ResumeLayout(false);
            this.panel4.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel panel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Chat_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Requests_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Pay_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Flat_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Home_btn;
        private System.Windows.Forms.Panel panel5;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Panel panel4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton Setting_btn;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ListView lvRequest;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton LogOut_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Services_btn;
        private System.Windows.Forms.ColumnHeader clmPhone;
        private System.Windows.Forms.ColumnHeader clmRoom;
        private System.Windows.Forms.ColumnHeader clmName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBrowse;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNoBrowse;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
    }
}